{{- if and (eq .Values.ingress_enabled "true") (eq .Values.apimgmt.enabled true)}}   
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: apimgmt
  namespace: {{ .Values.run.id }}
  annotations:
    nginx.ingress.kubernetes.io/ssl-passthrough: "1"
    nginx.ingress.kubernetes.io/ssl-redirect: "0"
spec:
  tls:
  - hosts:
    - apimgmt.{{ .Values.run.id }}.{{ .Values.ingress.host }}.nip.io
  rules:
  - host: apimgmt.{{ .Values.run.id }}.{{ .Values.ingress.host }}.nip.io
    http:
      paths: 
      - backend:
          serviceName: apimgmt
          servicePort: 8075

{{- end }}
