---
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.imageCredentials.name }}
  namespace: {{ .Values.run.id }}
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
type: kubernetes.io/dockerconfigjson
