{{- if and (eq .Values.ingress_enabled "true") (eq .Values.apimgr.enabled true) }}   
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: apimgr{{ .Values.apimgr.trafficPort }}
  namespace: {{ .Values.run.id }}
  annotations:
    nginx.ingress.kubernetes.io/ssl-passthrough: "1"
    nginx.ingress.kubernetes.io/ssl-redirect: "0"
spec:
  tls:
  - hosts:
    - apimgr{{ .Values.apimgr.trafficPort }}.{{ .Values.run.id }}.{{ .Values.ingress.host }}.nip.io
  rules:
  - host: apimgr{{ .Values.apimgr.trafficPort }}.{{ .Values.run.id }}.{{ .Values.ingress.host }}.nip.io
    http:
      paths: 
      - backend:
          serviceName: apimgr
          servicePort: {{ .Values.apimgr.trafficPort }}
{{- end }}
